#
# Travis Project Descriptor
#
# See http://docs.travis-ci.com/user/build-configuration/
#

# build matrix
language: python
python:
  - "3.6"
  - "3.8"

# commands to install dependencies
before_install:
  - sudo apt-get -y install pandoc

install:
  - "pip install -r dev-requirements.txt"

cache:
  directories:
    - $HOME/.cache/pip

# command to run tests
script: invoke test
