#
# Travis Project Descriptor
#
# See http://docs.travis-ci.com/user/build-configuration/
#

# build matrix
language: python
python:
    - "3.6"
    - "3.8"

# command to install dependencies
install:
    - "pip install -r dev-requirements.txt"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

# command to run tests
script: invoke test
