{% if "travis" in cookiecutter.features.replace(',', ' ').split() -%}
#
# Travis Project Descriptor
#
# See http://docs.travis-ci.com/user/build-configuration/
#

# build matrix
language: python
python:
    - "3.6"
#    - "pypy"
#matrix:
#    allow_failures:
#        - python: "3.5"

# command to install dependencies
install:
    - "pip install -r dev-requirements.txt"
    - "python setup.py develop -U"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

# command to run tests
script: invoke --echo --pty ci

# report to coveralls.io
after_success:
    - coveralls --rcfile project.d/coverage.cfg
{% endif -%}
